# Generated by Django 4.2.1 on 2023-05-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.AlterField(
            model_name='customers',
            name='country_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
